Fix a wrong code
Fix  a wrong code by OPPO causing compilation error in some rare conditions:

In file included from ../arch/arm64/kernel/asm-offsets.c:12:

In file included from ../include/linux/kexec.h:18:

In file included from ../include/linux/crash_core.h:6:

In file included from ../include/linux/elfcore.h:11:

In file included from ../include/linux/ptrace.h:10:

In file included from ../include/linux/pid_namespace.h:7:

../include/linux/mm.h:4537:8: error: no member named 'android_kabi_reserved2' in 'struct vm_area_struct'

 4537 |                 vma->android_kabi_reserved2 == THP_SWAP_PRIO_MAGIC;

      |                 ~~~  ^

1 error generated.